# In this example we create a KogitoBuild responsible to build our service from source and then deploy it as
# a KogitoRuntime reference. Since they have the same name, they will be bound together through the built image.
# the WebHook was added as an example
apiVersion: rhpam.kiegroup.org/v1
kind: KogitoBuild
metadata:
  name: ruleunit-quarkus-example
spec:
  buildImage: quay.io/yournamespace/custom-builder-image:0.11
  gitSource:
    contextDir: ruleunit-quarkus-example
    uri: https://github.com/kiegroup/kogito-examples
  runtime: quarkus
  runtimeImage: quay.io/yournamespace/custom-runtime-image:0.11
  type: RemoteSource
  webHooks:
    - type: "GitHub"
      secret: "test123"
---
apiVersion: rhpam.kiegroup.org/v1
kind: KogitoRuntime
metadata:
  name: ruleunit-quarkus-example
spec:
  replicas: 1
