apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - rhpam-kogito-operator-manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['olm.targetNamespaces']
          - name: BUILDER_IMAGE
            value: rhpam-kogito-builder-rhel8
          - name: RUNTIME_IMAGE
            value: rhpam-kogito-runtime-jvm-rhel8
          - name: IMAGE_NAMESPACE
            value: rhpam-7
          - name: IMAGE_REGISTRY
            value: registry.stage.redhat.io
      serviceAccountName: rhpam-kogito-operator-controller-manager
      terminationGracePeriodSeconds: 10
