# permissions for end users to edit kogitoinfras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitoinfra-editor-role
rules:
- apiGroups:
  - rhpam.kiegroup.org
  resources:
  - kogitoinfras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rhpam.kiegroup.org
  resources:
  - kogitoinfras/status
  verbs:
  - get
