# permissions for end users to view kogitoruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitoruntime-viewer-role
rules:
- apiGroups:
  - rhpam.kiegroup.org
  resources:
  - kogitoruntimes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rhpam.kiegroup.org
  resources:
  - kogitoruntimes/status
  verbs:
  - get
