review:
  - paths:
      - api/**
      - controllers/**
      - internal/**
    reviewers:
      - ricardozanini
      - spolti
      - vaibhavjainwiz
  - paths:
      - test/**
    reviewers:
      - sutaakar
      - radtriste
  - paths:
      - Jenkinsfile
    reviewers:
      - radtriste
      - msmagnanijr
default:
  - ricardozanini
  - spolti
