// Copyright 2021 Red Hat, Inc. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kiegroup/rhpam-kogito-operator/client/clientset/versioned/typed/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeV1 struct {
	*testing.Fake
}

func (c *FakeV1) KogitoBuilds(namespace string) v1.KogitoBuildInterface {
	return &FakeKogitoBuilds{c, namespace}
}

func (c *FakeV1) KogitoRuntimes(namespace string) v1.KogitoRuntimeInterface {
	return &FakeKogitoRuntimes{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
